// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibdxudnmxngltrkbfhfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZHh1ZG5teG5nbHRya2JmaGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjA3NzAsImV4cCI6MjA2NzUzNjc3MH0.rzgNRNqgf_mhQvvWP0dxFzLis8eExDnRjgjngmnOKpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});